### ISSUE TITLE
Problem with gridview infinite refresh

### ISSUE THREAD

**Issue by marciocamello** [kartik-v/yii2-widget-datepicker#66]
Before update to new version, using datepicker filter in grid view, generate error from search filter, and infinite refresh, please check this from others users. I am fix this back to old version.

**Comment by kartik-v** [comment]
No cannot reproduce your use case for grid or datepicker ... you may want to check if you have updated releases and you do not have any other proble.

The problem only will exist for timepicker widget because the source timepicker plugin triggers a change event on init which will trigger the filter and cause the infinite refresh.
